name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install

  test:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: ./jenkins/scripts/test.sh

  deliver:
    needs: [test]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deliver
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: sh './jenkins/scripts/deliver.sh'
      - run: sh './jenkins/scripts/kill.sh'
